# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "sysedr_handler_interface",
    hdrs = [
        "isysedr_handler.h",
    ],
    visibility = ["//score/datarouter/persistent_logging:__subpackages__"],
    deps = [
        "//score/datarouter:logparser",
    ],
)

cc_library(
    name = "sysedr_factory",
    hdrs = [
        "sysedr_factory.hpp",
    ],
    visibility = [
        "//score/datarouter/persistent_logging:__subpackages__",
        "//score/datarouter/test:__subpackages__",
    ],
    deps = [
        ":sysedr_handler_interface",
    ],
)
